using System;
using System.Collections.Generic;
using API.Mapper;
using Homeocentrum.Niga.NewAPI.Domain.Interfaces;
using Homeocentrum.Niga.NewAPI.Domain.Services;
using Homeocentrum.Niga.NewAPI.Domain.Implementation;
using Homeocentrum.Niga.NewAPI.Domain.Repositories;
using Homeocentrum.Niga.NewAPI.Domain.Interface;
using Homeocentrum.Niga.NewAPI.Domain.Business.Interface;
using Homeocentrum.Niga.NewAPI.Domain.Business.Implementation;
using Homeocentrum.Niga.NewAPI.Domain.Configuration;
using Homeocentrum.Niga.NewAPI.Domain.Services.AudioCaseIntelligence;
using Homeocentrum.Niga.NewAPI.Domain.Services.AudioCaseIntelligence.Embeddings;
using Homeocentrum.Niga.NewAPI.Domain.Services.AudioCaseIntelligence.Engines;
using Homeocentrum.Niga.NewAPI.Domain.Services.AudioCaseIntelligence.Enterprise;
using Homeocentrum.Niga.NewAPI.Domain.Services.AudioCaseIntelligence.Enterprise.Quality;
using Homeocentrum.Niga.NewAPI.Domain.Services.AudioCaseIntelligence.KnowledgeGraph;
using Homeocentrum.Niga.NewAPI.Domain.Services.AudioCaseIntelligence.Learning;
using Homeocentrum.Niga.NewAPI.Domain.Services.AudioCaseIntelligence.Merging;
using Homeocentrum.Niga.NewAPI.Domain.Services.AudioCaseIntelligence.Monitoring;
using Homeocentrum.Niga.NewAPI.Domain.Services.AudioCaseIntelligence.Orchestration;
using Homeocentrum.Niga.NewAPI.Domain.Services.AudioCaseIntelligence.Validation;
using Homeocentrum.Niga.NewAPI.Domain.Services.AudioCaseIntelligence.Validation.Enterprise;
using Homeocentrum.Niga.NewAPI.Domain.Services.AudioCaseIntelligence.V3.Engines;
using Homeocentrum.Niga.NewAPI.Domain.Services.AudioCaseIntelligence.V3.Orchestration;
using Homeocentrum.Niga.NewAPI.Domain.Services.AudioCaseIntelligence.V6;
using Homeocentrum.Niga.NewAPI.Domain.Services.AudioCaseIntelligence.RepertoryIntelligence;
using Homeocentrum.Niga.NewAPI.Domain.Services.AudioCaseIntelligence.RepertoryIntelligence.Confidence;
using Homeocentrum.Niga.NewAPI.Domain.Services.AudioCaseIntelligence.RepertoryIntelligence.Completion;
using Homeocentrum.Niga.NewAPI.Domain.Services.AudioCaseIntelligence.RepertoryIntelligence.Concepts;
using Homeocentrum.Niga.NewAPI.Domain.Services.AudioCaseIntelligence.RepertoryIntelligence.Extraction;
using Homeocentrum.Niga.NewAPI.Domain.Services.AudioCaseIntelligence.RepertoryIntelligence.Explanation;
using Homeocentrum.Niga.NewAPI.Domain.Services.AudioCaseIntelligence.RepertoryIntelligence.Learning;
using Homeocentrum.Niga.NewAPI.Domain.Services.AudioCaseIntelligence.RepertoryIntelligence.Normalization;
using Homeocentrum.Niga.NewAPI.Domain.Services.AudioCaseIntelligence.RepertoryIntelligence.Ontology;
using Homeocentrum.Niga.NewAPI.Domain.Services.AudioCaseIntelligence.RepertoryIntelligence.Ranking;
using Homeocentrum.Niga.NewAPI.Domain.Services.AudioCaseIntelligence.RepertoryIntelligence.Search;
using Homeocentrum.Niga.NewAPI.Domain.Services.AudioCaseIntelligence.RepertoryIntelligence.Synonyms;
using Homeocentrum.Niga.NewAPI.Domain.Services.AudioCaseIntelligence.RepertoryIntelligence.Validation;
using Homeocentrum.Niga.NewAPI.Domain.Services.AudioCaseIntelligence.RepertoryIntelligence.Vocabulary;
using Homeocentrum.Niga.NewAPI.Domain.Services.AudioCaseIntelligence.ECI.V8;
using Homeocentrum.Niga.NewAPI.Domain.Services.AudioCaseIntelligence.ECI.V8.Conversation;
using Homeocentrum.Niga.NewAPI.Domain.Services.AudioCaseIntelligence.ECI.V8.Database;
using Homeocentrum.Niga.NewAPI.Domain.Services.AudioCaseIntelligence.ECI.V8.Database.Modules;
using Homeocentrum.Niga.NewAPI.Domain.Services.AudioCaseIntelligence.ECI.V8.Extraction;
using Homeocentrum.Niga.NewAPI.Domain.Services.AudioCaseIntelligence.ECI.V8.Validation;
using Homeocentrum.Niga.NewAPI.Domain.Services.AiEmbeddingInfrastructure;
using Homeocentrum.Niga.NewAPI.Domain.Repositories.AiEmbeddingInfrastructure;
namespace Homeocentrum.Niga.NewAPI.Domain.Extensions
{
    
    public static class ApplicationServiceExtensions
    {
        public static IServiceCollection AddApplicationServices(this IServiceCollection services, IConfiguration config)
        {

            services.AddAutoMapper(typeof(AutoMapperProfiles).Assembly);
            services.AddScoped<ITokenService, TokenService>();
            services.AddSingleton<IJwtDenylistService, JwtDenylistService>();
            services.AddScoped<IAuditEventWriter, AuditEventWriter>();
            services.AddSingleton<ISignedFileUrlService, SignedFileUrlService>();
            // PRE-03 — Sms:Provider = Stub | Msg91 | Twilio (keys empty → stub log). OTP + appointment notices use ISmsSender.
            services.Configure<SmsOptions>(config.GetSection(SmsOptions.SectionName));
            services.Configure<TeleVideoOptions>(config.GetSection(TeleVideoOptions.SectionName));
            services.AddHttpClient("SmsVendor", client => client.Timeout = TimeSpan.FromSeconds(30));
            services.AddSingleton<INotificationOutbox, NotificationOutbox>();
            services.AddSingleton<ISmsSender, ConfigurableSmsSender>();
            services.AddSingleton<Homeocentrum.Niga.NewAPI.Domain.Services.Tele.StubTeleVideoVendor>();
            services.AddSingleton<Homeocentrum.Niga.NewAPI.Domain.Services.Tele.AgoraTeleVideoVendor>();
            services.AddSingleton<Homeocentrum.Niga.NewAPI.Domain.Services.Tele.ITeleVideoVendor, Homeocentrum.Niga.NewAPI.Domain.Services.Tele.ConfigurableTeleVideoVendor>();
            // Scoped: WhatsApp Meta typed client + SMS for reschedule/cancel/waitlist/tele notices.
            services.AddScoped<IAppointmentRescheduleNotifier, AppointmentRescheduleNotifier>();
            services.Configure<Homeocentrum.Niga.NewAPI.Domain.DTOs.SmtpSettingsModel>(config.GetSection("smtp"));
            services.AddScoped<IUserService, UserService>();
            services.AddScoped<ISectionRepository, SectionService>();
            services.AddScoped<ISubSectionRepository, SubSectionService>();
            services.AddScoped<IDateTime, DateTimeService>();
            services.AddScoped<IRemedyGradeRepository, RemedyGradeService>();
            services.AddScoped<IRemedyService, RemedyService>();
            services.AddScoped<IRepertorizationPageService, RepertorizationPageService>();
            services.AddScoped<ISeriousSideEffectService, SeriousSideEffectService>();
            services.AddScoped<IStateService, StateService>();
            services.AddScoped<ISubscriptionService, SubscriptionService>();
            services.AddScoped<ISubscriptionStatusService, SubscriptionStatusService>();
            services.AddScoped<IQualificationService, QualificationService>();
            services.AddScoped<IQuestionSectionService, QuestionSectionService>();
            services.AddScoped<IQuestionSubGroupService, QuestionSubGroupService>();
            services.AddScoped<IQuestionGroupService, QuestionGroupService>();
            services.AddScoped<IRubricRemedyDetailsService, RubricRemedyDetailsService>();
            services.AddSingleton<RubricRemedyImportQueue>();
            services.AddSingleton<IRubricRemedyImportQueue>(sp => sp.GetRequiredService<RubricRemedyImportQueue>());
            services.AddHostedService<RubricRemedyImportBackgroundService>();
            services.AddScoped<IDoctorDashBoardService, DoctorDashBoardService>();
            services.AddScoped<IPatientService, PatientService>();
            services.AddScoped<IBlogDetailService, BlogService>();
            services.AddScoped<INewsDetailService, NewsDetailService>();
            services.AddScoped<IPatientAppointmentService, PatientAppointmentService>();
            services.AddScoped<IS3Week3Service, S3Week3Service>();
            services.AddScoped<IS4Week4Service, S4Week4Service>();
            services.AddScoped<IPrescriptionService, PrescriptionService>();
            services.AddScoped<IDropdownListService, DropdownListService>();
            services.AddScoped<IAllopathicDrugService, AllopathicDrugService>();
            services.AddScoped<IMastersAPIService, MastersAPIService>();
            services.AddScoped<IPackageService, PackageService>();
            services.AddScoped<IMateriaMedicaRemediesDetails, MateriaMedicaRemediesDetailsService>();
            services.AddScoped<IClipboardRubricsService, ClipboardRubricsService>();
            services.AddScoped<IThreeDBodyPartSectionHotspotRepository, ThreeDBodyPartSectionHotspotService>();
            services.AddScoped<IThreeDBodyPartMeshKeyMasterRepository, ThreeDBodyPartMeshKeyMasterService>();
            services.AddScoped<IThreeDBodyPartSectionMasterRepository, ThreeDBodyPartSectionMasterService>();
            services.AddScoped<IReceptionStaffRepository, ReceptionStaffRepository>();
            services.AddScoped<IReceptionStaffService, ReceptionStaffService>();
            services.AddScoped<IPatientBoardBackupService, PatientBoardBackupService>();
            services.Configure<AudioCaseTakingOptions>(config.GetSection(AudioCaseTakingOptions.SectionName));
            services.Configure<RubricIntelligenceOptions>(config.GetSection(RubricIntelligenceOptions.SectionName));
            services.Configure<AppInfoOptions>(config.GetSection(AppInfoOptions.SectionName));
            services.Configure<OpenAiOptions>(config.GetSection(OpenAiOptions.SectionName));
            services.Configure<AzureOpenAiOptions>(config.GetSection(AzureOpenAiOptions.SectionName));
            services.AddHttpClient("OpenAI", (sp, client) =>
            {
                var options = sp.GetRequiredService<Microsoft.Extensions.Options.IOptions<OpenAiOptions>>().Value;
                client.BaseAddress = new Uri(options.BaseUrl.TrimEnd('/') + "/");
                client.Timeout = TimeSpan.FromMinutes(10);
            });
            services.AddScoped<IIntelligenceGptClient, IntelligenceGptClient>();
            services.AddScoped<ICaseUnderstandingEngine, CaseUnderstandingEngine>();
            services.AddScoped<IModalityDetectionEngine, ModalityDetectionEngine>();
            services.AddScoped<IConcomitantDetectionEngine, ConcomitantDetectionEngine>();
            services.AddScoped<IClinicalReasoningEngine, ClinicalReasoningEngine>();
            services.AddScoped<IHomeopathicReasoningEngine, HomeopathicReasoningEngine>();
            services.AddScoped<ICausationDetectionEngine, CausationDetectionEngine>();
            services.AddScoped<IHomeopathicWeightEngine, HomeopathicWeightEngine>();
            services.AddScoped<IMetaphorInterpretationEngine, MetaphorInterpretationEngine>();
            services.AddScoped<IRubricAliasEngine, RubricAliasEngine>();
            services.AddScoped<IEmbeddingClient, EmbeddingClient>();
            services.AddScoped<IRubricEmbeddingRepository, RubricEmbeddingRepository>();
            services.AddSingleton<IRubricEmbeddingMemoryCache, RubricEmbeddingMemoryCache>();
            services.AddSingleton<IFastClinicalQueryEmbeddingCache, FastClinicalQueryEmbeddingCache>();
            services.AddSingleton<IFastClinicalRubricCatalog, FastClinicalRubricCatalog>();
            services.AddSingleton<IAudioCaseSessionProcessingGate, AudioCaseSessionProcessingGate>();
            services.AddScoped<IEmbeddingSearchEngine, EmbeddingSearchEngine>();
            services.AddScoped<IConceptKeywordDiscoveryEngine, ConceptKeywordDiscoveryEngine>();
            services.AddScoped<IFastClinicalRetrievalOrchestrator, FastClinicalRetrievalOrchestrator>();
            services.AddScoped<IHybridRetrievalEngine, HybridRetrievalEngine>();
            services.AddScoped<IClinicalInferenceEngine, ClinicalInferenceEngine>();
            services.AddScoped<IExplainabilityEngine, ExplainabilityEngine>();
            services.AddScoped<IConfidenceScoringEngine, ConfidenceScoringEngine>();
            services.AddScoped<IRepertoryMappingRepository, RepertoryMappingRepository>();
            services.AddScoped<IRepertoryTierEngine, RepertoryTierEngine>();
            services.AddScoped<IPrimarySymptomEngine, PrimarySymptomEngine>();
            services.AddScoped<IEvidenceChainBuilder, EvidenceChainBuilder>();
            services.AddScoped<IRubricQualityScoringEngine, RubricQualityScoringEngine>();
            services.AddSingleton<IEnterpriseClinicalValidationPipeline, EnterpriseClinicalValidationPipeline>();
            services.AddScoped<IRubricEnterpriseEvidenceChainBuilder, EnterpriseRubricEvidenceChainBuilder>();
            services.AddScoped<IRubricEnterpriseEvidenceChainEnricher, EnterpriseRubricEvidenceChainEnricher>();
            services.AddScoped<IRubricEvidenceChainFeedbackLoader, RubricEvidenceChainFeedbackLoader>();
            services.AddScoped<IClinicalValidationEngine, ClinicalValidationEngine>();
            services.AddScoped<IConceptGraphRepository, ConceptGraphRepository>();
            services.AddScoped<IPatientMeaningGraphEngine, PatientMeaningGraphEngine>();
            services.AddScoped<ICaseDecompositionEngine, CaseDecompositionEngine>();
            services.AddScoped<IMultiSymptomDiscoveryEngine, MultiSymptomDiscoveryEngine>();
            services.AddScoped<ICategoryDiscoveryEngine, CategoryDiscoveryEngine>();
            services.AddScoped<IMetaphorUnderstandingEngine, MetaphorUnderstandingEngine>();
            services.AddScoped<IClinicalConceptEngineV3, ClinicalConceptEngineV3>();
            services.AddScoped<ISensationOntologyService, SensationOntologyService>();
            services.AddScoped<IHomeopathicConceptEngineV3, HomeopathicConceptEngineV3>();
            services.AddScoped<IRecallExpansionEngine, RecallExpansionEngine>();
            services.AddScoped<IMultiConceptDiscoveryEngine, MultiConceptDiscoveryEngine>();
            services.AddScoped<IConceptClusterEngine, ConceptClusterEngine>();
            services.AddScoped<IRubricDiscoveryEngineV3, RubricDiscoveryEngineV3>();
            services.AddScoped<IRubricCandidateEngine, RubricCandidateEngine>();
            services.AddScoped<IEnterpriseRubricDiscoveryEngine, EnterpriseRubricDiscoveryEngine>();
            services.AddScoped<IHierarchicalRepertorySearchEngine, HierarchicalRepertorySearchEngine>();
            services.AddScoped<PerConceptRubricSearchPipeline>();
            services.AddScoped<IEnterpriseHybridCompletionEngine, EnterpriseHybridCompletionEngine>();
            services.AddSingleton<IHybridCompletionAuditLogger, HybridCompletionAuditLogger>();
            services.AddScoped<ISqlAuthoritativeRepertorySearchEngine, SqlAuthoritativeRepertorySearchEngine>();
            services.AddScoped<V6PerSymptomDiscoveryPipeline>();
            services.AddScoped<IV6ClinicalReasoningEngine, V6ClinicalReasoningEngine>();
            services.AddScoped<IV6BenchmarkEvaluationService, V6BenchmarkEvaluationService>();
            services.AddScoped<IClinicalExtractionService, ClinicalExtractionService>();
            services.AddSingleton<ISynonymEngine, SynonymEngine>();
            services.AddScoped<IClinicalNormalizer, ClinicalNormalizer>();
            services.AddScoped<IHomeopathicVocabularyEngine, HomeopathicVocabularyEngine>();
            services.AddSingleton<IOntologyEngine, OntologyEngine>();
            services.AddScoped<ICandidateRubricSearchService, CandidateRubricSearchService>();
            services.AddScoped<IRubricRankingService, RubricRankingService>();
            services.AddScoped<IRubricCompletionEngine, RubricCompletionEngine>();
            services.AddScoped<IExplanationService, ExplanationService>();
            services.AddScoped<IConfidenceCalculator, ConfidenceCalculator>();
            services.AddScoped<IClinicalConceptService, ClinicalConceptService>();
            services.AddScoped<IContinuousLearningService, ContinuousLearningService>();
            services.AddScoped<IRepertoryIntelligenceOrchestrator, RepertoryIntelligenceOrchestrator>();
            services.AddScoped<IV7AccuracyBenchmarkService, V7AccuracyBenchmarkService>();
            services.AddSingleton<IEnterpriseRubricClinicalAuditLogger, EnterpriseRubricClinicalAuditLogger>();

            // ECI v8.0 (Phase A/B): new modular pipeline. Off by default via flags.
            services.AddScoped<IEciConversationParser, EciConversationParser>();
            services.AddScoped<IEciStructuredSymptomExtractor, EciStructuredSymptomExtractor>();
            services.AddScoped<IEciClinicalValidator, EciClinicalValidator>();
            services.AddScoped<IEciExactSqlSearchModule, ExactSqlSearchModule>();
            services.AddScoped<IEciSynonymSearchModule, SynonymSearchModule>();
            services.AddScoped<IEciOntologySearchModule, OntologySearchModule>();
            services.AddScoped<IEciFullTextSearchModule, FullTextSearchModule>();
            services.AddScoped<IEciEmbeddingSearchModule, EmbeddingSearchModule>();
            services.AddScoped<IEciHierarchySearchModule, HierarchySearchModule>();
            services.AddScoped<IEciBootstrapMappingSearchModule, BootstrapMappingSearchModule>();
            services.AddScoped<IEciHistoricalMappingSearchModule, HistoricalMappingSearchModule>();
            services.AddScoped<IEciCandidateMerger, CandidateMerger>();
            services.AddScoped<IEciRubricRanker, EciRubricRanker>();
            services.AddScoped<IEciEvidenceVerifier, EvidenceVerifier>();
            services.AddScoped<IEciExplainabilityGenerator, ExplainabilityGenerator>();
            services.AddScoped<IEciDatabaseIntelligenceEngine, EciDatabaseIntelligenceEngine>();
            services.AddScoped<IEciV8ClinicalIntelligenceOrchestrator, EciV8ClinicalIntelligenceOrchestrator>();

            services.AddScoped<EnterpriseRubricExpansionEngine>();
            services.AddScoped<EnterpriseRubricCandidateMerger>();
            services.AddScoped<IPipelineDiagnosticService, PipelineDiagnosticService>();
            services.AddScoped<IConceptGraphEvidenceEngine, ConceptGraphEvidenceEngine>();
            services.AddScoped<ITranscriptCoverageEngine, TranscriptCoverageEngine>();
            services.AddScoped<IMissingSymptomDetector, MissingSymptomDetector>();
            services.AddScoped<ICaseCompletenessScoringEngine, CaseCompletenessScoringEngine>();
            services.AddScoped<IConceptGraphOrchestrator, ConceptGraphOrchestrator>();
            services.AddScoped<AiSuggestedRubricReconciler>();
            services.AddScoped<IAudioCaseSessionProgressReporter, AudioCaseSessionProgressReporter>();
            services.AddSingleton<IRubricIntelligenceSettingsService, RubricIntelligenceSettingsService>();
            services.AddScoped<IDoctorFeedbackLearningEngine, DoctorFeedbackLearningEngine>();
            services.AddScoped<DoctorLearningContextResolver>();
            services.AddScoped<DoctorLearningSignalWriter>();
            services.AddScoped<IDoctorLearningWeightProvider, DoctorLearningWeightProvider>();
            services.AddScoped<IAiMonitoringDashboardService, AiMonitoringDashboardService>();
            services.AddScoped<AiMonitoringAuditLogger>();
            services.AddScoped<IEnterpriseKnowledgeGraphRepository, EnterpriseKnowledgeGraphRepository>();
            services.AddScoped<IKgGraphTraversalEngine, KgGraphTraversalEngine>();
            services.AddScoped<IKgExpressionResolverEngine, KgExpressionResolverEngine>();
            services.AddScoped<IKgEmbeddingBridge, KgEmbeddingBridge>();
            services.AddScoped<IKnowledgeGraphRanker, KnowledgeGraphRanker>();
            services.AddScoped<IKnowledgeGraphOrchestratorBridge, KnowledgeGraphOrchestratorBridge>();
            services.AddScoped<IKgFeedbackGraphWriter, KgFeedbackGraphWriter>();
            services.AddScoped<IKgBootstrapImporter, KgBootstrapImporter>();
            services.AddScoped<IKgRemedyProjectionSync, KgRemedyProjectionSync>();
            services.AddScoped<IRubricBenchmarkService, RubricBenchmarkService>();
            services.AddScoped<IRubricEmbeddingIndexerService, RubricEmbeddingIndexerService>();
            services.AddScoped<ISymptomExtractionEngine, SymptomExtractionEngine>();
            services.AddScoped<IAudioCaseIntelligenceRepository, AudioCaseIntelligenceRepository>();
            services.AddScoped<IRubricPipelineTelemetry, RubricPipelineTelemetry>();
            services.AddScoped<IRubricIntelligenceAdminService, RubricIntelligenceAdminService>();
            services.AddScoped<AudioCaseAiProcessor>();
            services.AddScoped<IRubricIntelligenceOrchestrator, RubricIntelligenceOrchestrator>();
            services.AddScoped<IAudioCaseTakingService, AudioCaseTakingService>();
            services.AddSingleton<AudioCaseTakingQueue>();
            services.AddSingleton<IAudioCaseTakingQueue>(sp => sp.GetRequiredService<AudioCaseTakingQueue>());
            services.AddHostedService<AudioCaseTakingBackgroundService>();
            services.AddHostedService<AudioCaseRetentionBackgroundService>();
            services.AddHostedService<AudioCaseZombieSessionSweeperBackgroundService>();
            services.AddHostedService<RubricEmbeddingIndexerBackgroundService>();

            services.Configure<AiEmbeddingInfrastructureOptions>(config.GetSection(AiEmbeddingInfrastructureOptions.SectionName));
            services.AddScoped<IAiEmbeddingUnitOfWork, AiEmbeddingUnitOfWork>();
            services.AddScoped<IAiEmbeddingVersionService, AiEmbeddingVersionService>();
            services.AddScoped<IAiEmbeddingJobService, AiEmbeddingJobService>();
            services.AddScoped<IAiEmbeddingQueueService, AiEmbeddingQueueService>();
            services.AddScoped<IAiEmbeddingAuditService, AiEmbeddingAuditService>();
            services.AddScoped<IAiEmbeddingStatisticsService, AiEmbeddingStatisticsService>();
            services.AddScoped<IAiEmbeddingInfrastructureService, AiEmbeddingInfrastructureService>();
            services.AddScoped<IRepertoryRubricCatalogReader, RepertoryRubricCatalogReader>();
            services.AddScoped<IRepertoryEmbeddingChangeDetector, RepertoryEmbeddingChangeDetector>();
            services.AddScoped<AiIncrementalEmbeddingQueueProcessor>();
            services.AddScoped<IAiIncrementalEmbeddingRefreshService, AiIncrementalEmbeddingRefreshService>();
            services.AddScoped<IAiEmbeddingRefreshJobRunner, AiEmbeddingRefreshJobRunner>();
            services.AddScoped<IAiEnterpriseRubricEmbeddingBuilder, AiEnterpriseRubricEmbeddingBuilder>();
            services.AddScoped<IAiEnterpriseConceptEmbeddingBuilder, AiEnterpriseConceptEmbeddingBuilder>();
            services.AddSingleton<IAiEmbeddingSemanticCacheReadiness, AiEmbeddingSemanticCacheReadiness>();
            services.AddSingleton<IAiConceptEmbeddingMemoryCache, AiConceptEmbeddingMemoryCache>();
            services.AddSingleton<IAiEnterpriseRubricEmbeddingMemoryCache, AiEnterpriseRubricEmbeddingMemoryCache>();
            services.AddScoped<EnterpriseConceptToRubricMapper>();
            services.AddScoped<IAiEnterpriseSemanticSearchService, AiEnterpriseSemanticSearchService>();
            services.AddHostedService<AiEnterpriseEmbeddingBuilderBackgroundService>();
            services.AddHostedService<AiEmbeddingBuildRecoveryBackgroundService>();
            services.AddHostedService<AiIncrementalEmbeddingRefreshBackgroundService>();
            services.AddHostedService<AiEmbeddingSemanticCacheWarmupBackgroundService>();

            // TODO S5: confirm WhatsApp Meta AccessToken / PhoneNumberId still valid (New-API appsettings WhatsAppMeta). S5 will use this client.
            services.Configure<WhatsAppMetaOptions>(config.GetSection(WhatsAppMetaOptions.SectionName));
            services.AddHttpClient<IWhatsAppMetaApiClient, WhatsAppMetaApiClient>();
            services.AddScoped<IWhatsAppRepository, WhatsAppRepository>();
            services.AddScoped<IWhatsAppService, WhatsAppService>();
            services.AddSingleton<WhatsAppBulkSendQueue>();
            services.AddSingleton<IWhatsAppBulkSendQueue>(sp => sp.GetRequiredService<WhatsAppBulkSendQueue>());
            services.AddHostedService<WhatsAppBulkSendBackgroundService>();
            services.AddHostedService<DailyIssueMatrixEmailService>();
            services.AddMvc()
        .AddRazorRuntimeCompilation();


            return services;
        }
    }
}